### ISSUE TITLE
Add total failures and errors count to root element "testsuites"

### ISSUE THREAD

**Issue by naasse** [bhecquet/newman-reporter-xunit#9]
This is an enhancement request.

I believe this would be universally helpful - it might be useful to have the aggregated total failure and error count at the root testsuites element. 

To avoid breaking changes for consumers, this probably deserves a flag to only apply optionally.

It's something I would like to see in my use case, so I'm going to update my fork and create a PR if you'd like it in the core product.

**Comment by bhecquet** [comment]
Thank you for this enhancement
